import React, {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check, CircleHelp,CarFront, X,ShoppingCart, Eye, EyeOff} from 'lucide-react';
import {farola,alternatives,currentCart,savedCart,mergeCarts,money} from './flow-data';

function Badge({type='fit',children}) {const Icon=type==='fit'?Check:type==='nofit'?X:CircleHelp;return <span className={`compatbadge ${type}`}><Icon size={14} aria-hidden="true"/>{children}</span>}
function Modal({children,title,onClose,mobile,description}) {const ref=useRef(null);const previous=useRef(document.activeElement);useEffect(()=>{ref.current.showModal();return()=>previous.current?.focus()},[]);return <dialog ref={ref} className={`flowmodal ${mobile?'mobilemodal':''}`} aria-labelledby={title} aria-describedby={description} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}>{children}</dialog>}
function Shell({children,cartCount=2,mobile,onCart}) {return <div className={`product flow-product${mobile?' mobile':''}`}><header className="header"><span className="brand">TORQUE<span className="brandmark">/</span></span><span className="descriptor">REPUESTOS AUTOMOTRICES</span><div className="headerlinks"><span>Colombia · COP</span><button className="cart" onClick={onCart} aria-label={`Ver carrito, ${cartCount} productos`}><ShoppingCart/><span>Carrito</span><b>{cartCount}</b></button></div></header>{children}<footer><span className="footerbrand">TORQUE</span><span>La pieza correcta, sin llamar a nadie.</span></footer></div>}
function Context(){return <div className="flow-context"><CarFront size={20}/><div><span className="eyebrow">TU VEHÍCULO ACTIVO</span><strong>Tivoli 2019 · Gasolina · Automática</strong></div></div>}
function ProductLine({item,children}){return <article className="flow-part"><div><h3>{item.name}</h3><span className="partcode">{item.code}</span><p>{item.brand}</p>{item.applies&&<p className="applicability">{item.applies}</p>}</div><div className="part-end"><strong className="price">{money(item.price)}</strong>{children}</div></article>}

export function ValidationScreens({screen,mobile,setMobile,onContinue}){
 const [fitState,setFitState]=useState('nofit');const [checkoutState,setCheckoutState]=useState('decision');
 return <><div className="reviewbar flow-review"><div className="reviewgroup">{screen==='fit'?[['nofit','A · No compatible'],['check','B · Verificar']].map(([id,label])=><button key={id} aria-pressed={fitState===id} onClick={()=>setFitState(id)}>{label}</button>):[['decision','A · Decisión'],['register','B · Registro'],['merged','C · Carritos fusionados'],['workshop','D · Taller en revisión']].map(([id,label])=><button key={id} aria-pressed={checkoutState===id} onClick={()=>setCheckoutState(id)}>{label}</button>)}</div><div className="reviewgroup"><button aria-pressed={!mobile} onClick={()=>setMobile(false)}>Desktop · 1440</button><button aria-pressed={mobile} onClick={()=>setMobile(true)}>Móvil · 390</button></div></div>{screen==='fit'?<FitScreen key={fitState} mode={fitState} mobile={mobile}/>:<Checkout key={checkoutState} initial={checkoutState} mobile={mobile} onContinue={onContinue}/>}<p className="prototype-note">Prototipo · Referencias, compatibilidad, precios y cuentas de muestra. No se envían datos ni se procesan compras. Plazo de verificación propuesto: 1 día hábil.</p></>
}
function FitScreen({mode,mobile}){
 const [open,setOpen]=useState(false);const [item,setItem]=useState(farola);const [items,setItems]=useState([]);const [notice,setNotice]=useState('');const [advisor,setAdvisor]=useState(false);const [cart,setCart]=useState(false);const [showAlternatives,setShowAlternatives]=useState(false);const altRef=useRef(null);
 useEffect(()=>{if(showAlternatives)altRef.current?.focus()},[showAlternatives]);
 const add=p=>{setItems(list=>{const found=list.find(i=>i.code===p.code);return found?list.map(i=>i.code===p.code?{...i,qty:i.qty+1}:i):[...list,{...p,qty:1}]});setOpen(false);setNotice(`${p.name} agregada al carrito.`)};
 return <Shell mobile={mobile} cartCount={items.reduce((s,p)=>s+p.qty,0)} onCart={()=>setCart(true)}><Context/><main className="flow-main"><div className="flow-breadcrumb">Catálogo / Eléctrico e iluminación / Farolas</div><div className="flow-heading"><div><span className="eyebrow">ILUMINACIÓN / DELANTERA</span><h1>{item.name}</h1><span className="partcode">REF. {item.code}</span></div><Badge type={item!==farola?'fit':mode}>{item!==farola?'Compatible con tu Tivoli':mode==='nofit'?'No compatible con tu Tivoli':'Verificar compatibilidad'}</Badge></div><div className="piece-detail"><div><span className="eyebrow">APLICACIÓN REGISTRADA</span><h2>{item.applies}</h2><p>{item.brand} · Unidad · Lado derecho</p><p className="detail-note">Comprueba el lado y el tipo de iluminación antes de comprar.</p></div><div className="buy-panel"><strong className="big-price">{money(item.price)}</strong><span>Precio por unidad · IVA incluido</span><button className="primary" onClick={()=>item===farola?setOpen(true):add(item)}>Agregar al carrito <ArrowRight size={18}/></button></div></div>{notice&&<div className="flow-success" role="status"><Check size={20}/><span>{notice}</span><button className="textbutton" onClick={()=>setCart(true)}>Ver carrito</button></div>}
 {showAlternatives&&<section className="inline-alternatives"><h2 ref={altRef} tabIndex={-1}>Farolas para tu Tivoli 2019</h2><p>Gasolina · Automática · Iluminación halógena</p>{alternatives.map(p=><ProductLine key={p.code} item={p}><Badge>Compatible</Badge><button className="secondary" onClick={()=>{setItem(p);setNotice('');}}>Ver esta pieza</button></ProductLine>)}</section>}
 <div className="flow-bottomnote">¿Compras para otro vehículo? Puedes agregar la pieza y mantener tu Tivoli activo.</div></main>
 {open&&<Modal title="fit-title" description="fit-description" onClose={()=>setOpen(false)} mobile={mobile}><div className="modal-top"><span className="eyebrow">ANTES DE AGREGAR</span><button className="iconbutton" aria-label="Cerrar advertencia" onClick={()=>setOpen(false)}><X/></button></div><Badge type={mode}>{mode==='nofit'?'No compatible':'Verificar compatibilidad'}</Badge><h2 id="fit-title" className="modal-heading">{mode==='nofit'?'Esta farola no aplica para tu Tivoli.':'Todavía no podemos confirmar si aplica.'}</h2><p id="fit-description">{mode==='nofit'?'La aplicación registrada corresponde a un Korando. Si compras para otro carro, puedes continuar.':'No tenemos cargado el dato de compatibilidad de esta referencia con tu Tivoli. Esto no significa que no sirva.'}</p><div className="warning-piece"><ProductLine item={farola}/></div><Context/>{mode==='nofit'?<section className="modal-alternatives"><h3>Estas dos opciones sí aplican para tu Tivoli</h3><p>Para iluminación halógena. Confirma el tipo de farola de tu vehículo.</p>{alternatives.map(p=><ProductLine key={p.code} item={p}><Badge>Compatible</Badge></ProductLine>)}</section>:<section className="advisor-info"><h3>Confírmalo con un asesor</h3><p>Ten a mano el VIN o una foto de la referencia de tu farola. El asesor podrá verificar la aplicación antes de que compres.</p><span className="partcode">CONSULTA / {farola.code} · TIVOLI 2019</span></section>}<div className="modal-actions"><button className="primary" onClick={()=>{setOpen(false);if(mode==='nofit')setShowAlternatives(true);else setAdvisor(true)}}>{mode==='nofit'?'Ver la que sirve para mi Tivoli':'Consultar con un asesor'}<ArrowRight size={18}/></button><button className="secondary" onClick={()=>add(farola)}>Agregar de todos modos</button></div><p className="modal-foot">Tú decides. Tu vehículo activo no cambiará.</p></Modal>}
 {advisor&&<Modal title="advisor-title" onClose={()=>setAdvisor(false)} mobile={mobile}><div className="modal-top"><span className="eyebrow">CONSULTA DE COMPATIBILIDAD</span><button className="iconbutton" aria-label="Cerrar consulta" onClick={()=>setAdvisor(false)}><X/></button></div><h2 id="advisor-title">Información para el asesor</h2><div className="advisor-info"><p>¿La farola derecha {farola.code} aplica para mi Tivoli 2019, gasolina, automática?</p><p>Adjuntaría el VIN o una foto de la referencia para confirmar.</p></div><p className="demo-callout">Demostración: la consulta está preparada. No se ha enviado a un asesor; falta conectar el canal de atención.</p><button className="secondary" onClick={()=>setAdvisor(false)}>Volver a la pieza</button></Modal>}
 {cart&&<Modal title="fit-cart" onClose={()=>setCart(false)} mobile={mobile}><div className="modal-top"><h2 id="fit-cart">Tu carrito</h2><button className="iconbutton" aria-label="Cerrar carrito" onClick={()=>setCart(false)}><X/></button></div>{items.length?items.map(p=><ProductLine key={p.code} item={p}><span>Cantidad: {p.qty}</span></ProductLine>):<p>Aún no has agregado piezas.</p>}<div className="cart-total"><span>Subtotal</span><strong>{money(items.reduce((s,p)=>s+p.price*p.qty,0))}</strong></div></Modal>}
 </Shell>
}

function Checkout({initial,mobile,onContinue}){
 const [stage,setStage]=useState(initial);const [mode,setMode]=useState(initial==='register'?'register':'login');const [name,setName]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [showPassword,setShowPassword]=useState(false);const [workshop,setWorkshop]=useState(initial==='workshop');const [errors,setErrors]=useState({});const [existing,setExisting]=useState(false);const [merged,setMerged]=useState(initial==='merged');const [garage,setGarage]=useState(false);const [message,setMessage]=useState('');const [next,setNext]=useState(false);const [recover,setRecover]=useState(false);const emailRef=useRef(null);const passwordRef=useRef(null);const statusRef=useRef(null);const cartRef=useRef(null);
 const cart=merged?mergeCarts(currentCart,savedCart):currentCart;const total=cart.reduce((s,p)=>s+p.price*p.qty,0);
 useEffect(()=>{if(stage==='merged'||stage==='workshop')statusRef.current?.focus()},[stage]);
 function submit(e){e.preventDefault();const err={};if(mode==='register'&&name.trim().length<3)err.name='Escribe tu nombre completo.';if(mode==='register'&&!/^3\d{9}$/.test(phone))err.phone='Escribe un celular de 10 dígitos que comience por 3.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()))err.email='Escribe un correo válido, por ejemplo nombre@correo.com.';if(!password)err.password='Escribe tu contraseña.';else if(mode==='register'&&password.length<8)err.password='Usa al menos 8 caracteres.';setErrors(err);if(Object.keys(err).length){(err.email?emailRef:passwordRef).current?.focus();return}if(mode==='register'&&email.trim().toLowerCase()==='cliente@torque.co'){setExisting(true);return}setMerged(mode==='login');setStage(workshop&&mode==='register'?'workshop':'merged');setExisting(false)}
 function switchMode(value){setMode(value);setStage(value==='register'?'register':'decision');setErrors({});setExisting(false)}
 return <Shell mobile={mobile} cartCount={cart.reduce((s,p)=>s+p.qty,0)} onCart={()=>{cartRef.current?.scrollIntoView({block:'center',behavior:'smooth'});cartRef.current?.focus()}}><div className="mobile-cart-peek"><div><strong>{cart.length} referencias · {money(total)}</strong><small>{stage === 'workshop' ? 'Precios públicos · Taller pendiente' : 'Tu carrito sigue aquí'}</small></div><button className="textbutton" onClick={()=>{cartRef.current?.scrollIntoView({block:'start',behavior:'smooth'});cartRef.current?.focus()}}>Ver resumen</button></div><main className="checkout-main"><div className="checkout-top"><span className="eyebrow">FINALIZAR COMPRA</span><span>Tu carrito se conserva durante este paso.</span></div><ol className="checkout-steps" aria-label="Pasos de la compra"><li aria-current="step"><b>01</b> Tu cuenta</li><li><b>02</b> Entrega</li><li><b>03</b> Pago</li></ol><div className="checkout-grid"><section className="account-section">
 {(stage==='decision'||stage==='register')?<><span className="eyebrow">PASO 01 / TU CUENTA</span><h1>{mode==='register'?'Crea tu cuenta. Conserva tu carrito.':'Tu compra continúa aquí.'}</h1><p>Accede para seguir con la entrega y el pago.</p><div className="account-tabs" aria-label="Acceso a tu cuenta"><button aria-pressed={mode==='login'} onClick={()=>switchMode('login')}>Iniciar sesión</button><button aria-pressed={mode==='register'} onClick={()=>switchMode('register')}>Crear cuenta</button></div><form noValidate onSubmit={submit}>{mode==='register'&&<><div className="account-field"><label htmlFor="account-name">Nombre completo</label><input id="account-name" value={name} autoComplete="name" aria-invalid={!!errors.name} aria-describedby={errors.name?'name-error':undefined} onChange={e=>{setName(e.target.value);setErrors({...errors,name:null})}}/>{errors.name&&<span className="field-error" id="name-error" role="alert">× {errors.name}</span>}</div><div className="account-field"><label htmlFor="account-phone">Celular</label><input id="account-phone" type="tel" value={phone} autoComplete="tel" aria-invalid={!!errors.phone} aria-describedby={errors.phone?'phone-error':'phone-help'} onChange={e=>{setPhone(e.target.value);setErrors({...errors,phone:null})}}/><span id="phone-help" className="field-help">Lo usamos solo para novedades de entrega.</span>{errors.phone&&<span className="field-error" id="phone-error" role="alert">× {errors.phone}</span>}</div></>}<div className="account-field"><label htmlFor="account-email">Correo electrónico</label><input ref={emailRef} id="account-email" type="email" autoComplete="email" value={email} aria-invalid={!!errors.email} aria-describedby={errors.email?'email-error':'email-help'} onChange={e=>{setEmail(e.target.value);setExisting(false);setErrors({...errors,email:null})}}/><span id="email-help" className="field-help">Aquí recibirás la confirmación y el estado de tu pedido.</span>{errors.email&&<span className="field-error" id="email-error" role="alert">× {errors.email}</span>}</div>
 {existing&&<div className="existing-account" role="status"><strong>Ya tienes una cuenta con este correo.</strong><p>Inicia sesión para continuar. Conservaremos las piezas de tu carrito.</p><button className="secondary" type="button" onClick={()=>{switchMode('login');setPassword('');passwordRef.current?.focus()}}>Iniciar sesión con este correo <ArrowRight size={16}/></button></div>}
 <div className="account-field"><label htmlFor="account-password">Contraseña{mode==='register'&&<span> · Mínimo 8 caracteres</span>}</label><div className="password-field"><input ref={passwordRef} id="account-password" type={showPassword?'text':'password'} autoComplete={mode==='register'?'new-password':'current-password'} value={password} aria-invalid={!!errors.password} aria-describedby={errors.password?'password-error':undefined} onChange={e=>{setPassword(e.target.value);setErrors({...errors,password:null})}}/><button className="iconbutton" type="button" onClick={()=>setShowPassword(!showPassword)} aria-label={showPassword?'Ocultar contraseña':'Mostrar contraseña'}>{showPassword?<EyeOff/>:<Eye/>}</button></div>{errors.password&&<span className="field-error" id="password-error" role="alert">× {errors.password}</span>}</div>
 {mode==='register'?<><label className="workshop-check"><input type="checkbox" checked={workshop} onChange={e=>setWorkshop(e.target.checked)}/><span><strong>Soy taller o empresa</strong><small>Solicita precios para tu negocio. Verificamos tu perfil en máximo 1 día hábil.</small></span></label><div className="minimal-data"><strong>Cuatro datos indispensables.</strong><p>Nombre para el pedido, celular para novedades de entrega, correo para identificarte y contraseña para proteger el acceso. Dirección y facturación se piden después.</p></div></>:<button type="button" className="textbutton forgot" onClick={()=>setRecover(true)}>Olvidé mi contraseña</button>}
 <button className="primary account-submit">{mode==='register'?'Crear cuenta y continuar':'Iniciar sesión y continuar'}<ArrowRight size={18}/></button></form><div className="demo-credentials"><span className="eyebrow">DATOS PARA PROBAR</span><p>Correo existente: <span className="partcode">cliente@torque.co</span><br/>Ingreso simulado: cualquier contraseña de 8 caracteres. No uses datos reales.</p><button className="textbutton" onClick={()=>{setName('Andrés Martínez');setPhone('3001234567');setEmail('cliente@torque.co');setPassword('Torque123');setErrors({});}}>Usar datos de prueba</button></div></>:<><span className="eyebrow">PASO 01 / CUENTA LISTA</span><h1 ref={statusRef} tabIndex={-1}>{stage==='workshop'?'Tu solicitud de taller está en revisión.':'Ya puedes continuar con tu compra.'}</h1>
 {stage==='workshop'?<div className="workshop-status"><Badge type="check">Pendiente de verificación</Badge><h2>Ahora ves precios públicos.</h2><p>Estos todavía no son tus precios de taller. Se activarán cuando verifiquemos tu negocio.</p><dl><div><dt>Plazo de respuesta</dt><dd>Máximo 1 día hábil</dd></div><div><dt>Si te registras un sábado</dt><dd>Revisamos tu solicitud el lunes, o el siguiente día hábil si es festivo.</dd></div><div><dt>Cómo te avisamos</dt><dd>Te enviaremos un correo a <strong>{email||'taller@ejemplo.co'}</strong> cuando tu clasificación esté lista.</dd></div></dl><div className="workshop-reassurance">Tu carrito sigue aquí. Puedes esperar la verificación y revisar tus precios antes de pagar.</div><p className="public-now">Si decides comprar ahora, se aplican los precios públicos de este resumen.</p></div>:<div className="merge-confirmation" role="status"><Check size={22}/><div><strong>{merged?'Unimos tus carritos sin duplicar referencias.':'Tu cuenta está creada y tu carrito sigue aquí.'}</strong><p>{merged?'2 referencias de esta compra + 1 de tu carrito anterior. El filtro de aceite estaba en ambos: conservamos 1 unidad.':'Conservamos las 2 referencias de esta compra.'}</p>{merged&&<small>Para una referencia repetida, conservamos la cantidad mayor de ambos carritos.</small>}</div></div>}
 <div className="garage-offer"><CarFront size={22}/><div><h3>{garage?'Tivoli guardado en tu garaje':'¿Guardamos tu Tivoli en el garaje?'}</h3><p>Tivoli 2019 · Gasolina · Automática</p><p>{garage?'Podrás seleccionarlo en tu próxima compra.':'Así no tendrás que identificarlo en tu próxima compra.'}</p><button className="secondary" onClick={()=>setGarage(!garage)}>{garage?'Quitar del garaje':'Guardar mi Tivoli'}</button><span className="garage-status" role="status">{garage?'✓ Guardado en esta sesión de prueba':''}</span></div></div>
 {stage==='workshop'?<div className="workshop-actions"><button className="primary" onClick={()=>setMessage('Tu carrito queda conservado en esta sesión de prueba. La notificación por correo se simula; no se ha enviado ningún mensaje.')}>Esperar mis precios de taller</button><button className="secondary" onClick={()=>onContinue ? onContinue() : setNext(true)}>Continuar con precios públicos <ArrowRight size={16}/></button></div>:<button className="primary account-submit" onClick={()=>onContinue ? onContinue() : setNext(true)}>Continuar a entrega <ArrowRight size={18}/></button>}{message&&<p className="flow-success" role="status">✓ {message}</p>}</>}
 </section><aside className="order-summary" ref={cartRef} tabIndex={-1} aria-label="Resumen de tu carrito"><div className="summary-heading"><h2>Tu carrito</h2><span>{cart.length} referencias</span></div>{stage==='workshop'&&<div className="public-price-label">PRECIOS PÚBLICOS<span>Tarifa de taller pendiente de activación</span></div>}<div className="summary-vehicle"><CarFront size={18}/><span>Tivoli 2019 · Gasolina · Automática</span></div>{cart.map(p=><article className="summary-row" key={p.code}><div><h3>{p.name}</h3><span className="partcode">{p.code}</span><p>{p.qty} unidad · {p.brand}</p>{merged&&p.code==='8123-45679'&&<span className="previous-cart">De tu carrito anterior</span>}</div><strong>{money(p.price*p.qty)}</strong></article>)}<div className="summary-calculation"><div><span>Subtotal · IVA incluido</span><strong>{money(total)}</strong></div><div><span>Envío</span><span>Se calcula en entrega</span></div></div><div className="cart-total"><span>Total de productos</span><strong>{money(total)}</strong></div><p className="summary-note">El envío se suma en el siguiente paso. Revisa el total antes de pagar.</p><div className="summary-preserved"><Check size={16}/> Tus piezas siguen en el carrito.</div></aside></div></main>
 {recover&&<Modal title="recover-title" mobile={mobile} onClose={()=>setRecover(false)}><div className="modal-top"><h2 id="recover-title">Recuperar acceso</h2><button className="iconbutton" aria-label="Cerrar recuperación" onClick={()=>setRecover(false)}><X/></button></div><p>En la tienda recibirás un enlace en tu correo para crear una nueva contraseña.</p><div className="demo-callout">Recuperación simulada. No se ha enviado ningún correo.</div><button className="secondary" onClick={()=>setRecover(false)}>Volver a iniciar sesión</button></Modal>}
 {next&&<Modal title="next-title" mobile={mobile} onClose={()=>setNext(false)}><div className="modal-top"><span className="eyebrow">PASO 01 COMPLETADO</span><button className="iconbutton" aria-label="Cerrar" onClick={()=>setNext(false)}><X/></button></div><h2 id="next-title">Tu cuenta y tu carrito están listos.</h2><p className="demo-callout">Aquí continúa el paso de entrega. Esta pantalla todavía no forma parte del prototipo.</p><p>{cart.length} referencias · {money(total)} en productos{stage==='workshop'?' · Precios públicos':''}</p><button className="secondary" onClick={()=>setNext(false)}>Volver al resumen</button></Modal>}
 </Shell>
}


