import React,{useState,useEffect,useRef} from 'react';
import {X,ArrowRight,ArrowLeft,CarFront,Check,Hash,ListChecks,CircleHelp,Trash2} from 'lucide-react';
import {initialGarage,modelPhoto,guideSteps,validOptions} from './catalog-data';
export function VehicleWizard({onClose,onSave,mobile=false,start='methods'}){
 const [view,setView]=useState(start);const [method,setMethod]=useState('plate');const [value,setValue]=useState('');const [error,setError]=useState('');const [index,setIndex]=useState(0);const [draft,setDraft]=useState({});const [version,setVersion]=useState('');const dialog=useRef(null);const title=useRef(null);const returnFocus=useRef(document.activeElement);
 useEffect(()=>{dialog.current.showModal();document.body.style.overflow='hidden';return()=>{document.body.style.overflow='';returnFocus.current?.focus()}},[]);
 useEffect(()=>{title.current?.focus()},[view,index]);
 function lookup(e){e.preventDefault();const v=value.toUpperCase().replace(/\s/g,'');if(method==='plate'&&!/^[A-Z]{3}\d{3}$/.test(v)){setError('Escribe 3 letras y 3 números. Ejemplo de prueba: ABC123.');return}if(method==='vin'&&!/^[A-HJ-NPR-Z0-9]{17}$/.test(v)){setError('El VIN debe tener 17 caracteres, sin I, O ni Q.');return}setError('');setValue(v);setView(v==='ABC123'||v==='KPA10000000000001'?'found':'notfound')}
 function guided(){setDraft({});setIndex(0);setError('');setView('guide')}
 function select(option){const key=guideSteps[index][0];const next={...draft,[key]:option};guideSteps.slice(index+1).forEach(([k])=>delete next[k]);setDraft(next);if(index===5){setVersion('');setView('versions')}else setIndex(index+1)}
 function save(uncertain=false){const found=view==='found';const base=found?initialGarage[0]:{...draft,plate:method==='plate'&&value?value:'Sin placa'};onSave({...base,id:`${base.model.toLowerCase()}-${base.year}-${base.plate}`,version:found?'Comfort · Halógena':uncertain?'Versión por confirmar':version,uncertain});onClose()}
 const heading={methods:'Identifica tu vehículo.',entry:method==='plate'?'Buscar por placa.':'Buscar por VIN.',found:'Encontramos este vehículo.',notfound:'No pudimos resolver la consulta.',guide:`Selecciona ${guideSteps[index][1].toLowerCase()}.`,versions:'Una última diferencia: el equipamiento.'}[view];
 return <dialog ref={dialog} className={`vehicle-sheet${mobile?' simulate-mobile-sheet':''}`} aria-labelledby="identify-heading" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="sheet-top"><span className="eyebrow">IDENTIFICAR MI VEHÍCULO</span><button className="iconbutton" onClick={onClose} aria-label="Cerrar identificación"><X/></button></div><div className="sheet-body"><h2 id="identify-heading" ref={title} tabIndex={-1}>{heading}</h2>
 {view==='methods'&&<><p>Elige el método que te resulte más fácil. Puedes cerrar y seguir buscando en cualquier momento.</p><div className="identify-methods">{[['plate','Por placa','La forma más rápida.',Hash],['vin','Por VIN','Los 17 caracteres del chasis.',CarFront],['guide','Paso a paso','Sin documentos a la mano.',ListChecks]].map(([id,label,desc,Icon])=><button key={id} onClick={()=>{if(id==='guide')guided();else{setMethod(id);setView('entry');setValue('');setError('')}}}><Icon/><span><strong>{label}</strong><small>{desc}</small></span><ArrowRight/></button>)}</div><div className="sheet-demo">Consulta simulada. Solo se resuelven la placa ABC123 y el VIN KPA10000000000001.</div></>}
 {view==='entry'&&<><p>{method==='plate'?'Consulta los datos y confírmalos antes de usarlos.':'Lo encuentras en la tarjeta de propiedad o en la base del parabrisas.'}</p><form onSubmit={lookup} noValidate><div className="account-field"><label htmlFor="vehicle-lookup">{method==='plate'?'Placa':'VIN / Número de chasis'}</label><input id="vehicle-lookup" className="lookup-input" value={value} onChange={e=>{setValue(e.target.value.toUpperCase());setError('')}} maxLength={method==='plate'?6:17} autoComplete="off" aria-invalid={!!error} aria-describedby={error?'lookup-error':'lookup-help'}/><span id="lookup-help" className="field-help">Dato de prueba: {method==='plate'?'ABC123':'KPA10000000000001'}</span>{error&&<span id="lookup-error" className="field-error" role="alert">× {error}</span>}</div><button className="primary sheet-primary">Buscar vehículo <ArrowRight/></button></form><div className="lookup-examples"><button className="textbutton" onClick={()=>setValue(method==='plate'?'ABC123':'KPA10000000000001')}>Usar ejemplo encontrado</button><button className="textbutton" onClick={()=>setValue(method==='plate'?'XYZ789':'KPA99999999999999')}>Usar ejemplo sin resultado</button></div><button className="textbutton" onClick={()=>setView('methods')}>← Cambiar método</button></>}
 {view==='found'&&<><p>Revisa que corresponda a tu carro. Una placa encontrada no reemplaza tu confirmación.</p><img className="found-car" src={modelPhoto('Tivoli')} alt="SsangYong Tivoli blanco, vista frontal de tres cuartos"/><div className="resolved-vehicle"><span className="plate">{method==='plate'?value:'ABC123'}</span><h3>SsangYong Tivoli 2019</h3><dl><div><dt>Caja</dt><dd>Automática</dd></div><div><dt>Combustible</dt><dd>Gasolina</dd></div><div><dt>Tracción</dt><dd>4×2</dd></div><div><dt>Versión</dt><dd>Comfort · Halógena</dd></div></dl></div><button className="primary sheet-primary" onClick={()=>save()}>Sí, este es mi vehículo <Check/></button><button className="secondary sheet-secondary" onClick={guided}>Los datos no coinciden · Seleccionar paso a paso</button></>}
 {view==='notfound'&&<><div className="lookup-failed"><CircleHelp/><div><strong>{method==='plate'?`No encontramos la placa ${value}.`:'No encontramos información para este VIN.'}</strong><p>Puedes identificar tu vehículo paso a paso. No necesitas volver a consultar ni tener la tarjeta de propiedad.</p></div></div><button className="primary sheet-primary" onClick={guided}>Seleccionar paso a paso <ArrowRight/></button><button className="secondary sheet-secondary" onClick={()=>setView('entry')}>Corregir {method==='plate'?'placa':'VIN'}</button></>}
 {view==='guide'&&<><div className="guide-progress"><span>PASO {index+1} DE 6</span><strong>{guideSteps[index][1]}</strong><div>{guideSteps.map(([key],i)=><span key={key} className={i<=index?'complete':''}/>)}</div></div><div className="guide-trail">{guideSteps.slice(0,index).map(([k,label],i)=><button key={k} onClick={()=>setIndex(i)}>{label}: <strong>{draft[k]}</strong></button>)}</div><p>Opciones disponibles para la selección anterior.</p><div className="guide-options">{validOptions(guideSteps[index][0],draft).map(option=><button key={option} onClick={()=>select(option)}>{option}<ArrowRight size={18}/></button>)}</div><button className="textbutton" onClick={()=>index?setIndex(index-1):setView('methods')}><ArrowLeft size={16}/> Atrás</button></>}
 {view==='versions'&&<><span className="eyebrow">{draft.brand} {draft.model} {draft.year} · {draft.transmission} · {draft.fuel} · {draft.traction}</span><p>Estas versiones comparten motor y transmisión. La diferencia está en el equipamiento y puede no aparecer en la tarjeta de propiedad.</p><div className="version-grid">{[['Comfort · Halógena',['Farolas halógenas con reflector','Ajuste manual de altura de farolas','Sin lavafaros']],['Premium · Proyector',['Farolas con proyector','Ajuste automático de altura','Con lavafaros']]].map(([name,features])=><label className={`version-option ${version===name?'selected':''}`} key={name}><input type="radio" name="version" checked={version===name} onChange={()=>setVersion(name)}/><strong>{name}</strong><ul>{features.map(f=><li key={f}>{f}</li>)}</ul></label>)}</div><button className="primary sheet-primary" disabled={!version} onClick={()=>save()}>Usar la versión seleccionada <Check/></button><div className="uncertain-choice"><CircleHelp/><div><strong>No necesitas adivinar.</strong><p>Si continúas sin versión, las piezas que dependen del equipamiento quedarán en “Verificar compatibilidad”.</p><button className="secondary" onClick={()=>save(true)}>No sé cuál es la mía — continuar así</button></div></div><button className="textbutton" onClick={()=>{setView('guide');setIndex(5)}}>← Revisar selección</button></>}
 </div><div className="sheet-footer">Identificación de prueba · Puedes continuar sin identificar tu vehículo.</div></dialog>
}
export function Garage({vehicles,setVehicles,active,onActivate,onIdentify,mobile}){const [removed,setRemoved]=useState(null);return <div className={`product garage-product${mobile?' mobile':''}`}><header className="header"><span className="brand">TORQUE<span className="brandmark">/</span></span><span className="descriptor">MI CUENTA / MI GARAJE</span></header><main className="garage-main"><div className="garage-heading"><div><span className="eyebrow">TUS VEHÍCULOS</span><h1>Mi garaje</h1><p>Activa el vehículo para el que estás buscando repuestos.</p></div><button className="secondary" onClick={onIdentify}>Identificar otro vehículo <ArrowRight size={16}/></button></div>{removed&&<div className="garage-notice" role="status">Quitaste {removed.model} {removed.year} del garaje.<button className="textbutton" onClick={()=>{setVehicles([...vehicles,removed]);setRemoved(null)}}>Deshacer</button></div>}<div className="garage-grid">{vehicles.map(v=><article className={`garage-car ${active?.id===v.id?'is-active':''}`} key={v.id}><div className="garage-photo"><img src={modelPhoto(v.model)} alt={`SsangYong ${v.model} ${v.year}`}/>{active?.id===v.id&&<span className="compatbadge fit"><Check/> Vehículo activo</span>}</div><div className="garage-info"><span className="plate">{v.plate}</span><h2>{v.model} {v.year}</h2><p>{v.fuel} · {v.transmission} · {v.traction}</p><span className="garage-version">{v.version}</span><div className="garage-actions"><button className={active?.id===v.id?'secondary':'primary'} disabled={active?.id===v.id} onClick={()=>onActivate(v)}>{active?.id===v.id?'✓ Activo':'Activar vehículo'}</button><button className="textbutton remove-vehicle" onClick={()=>{setRemoved(v);setVehicles(vehicles.filter(p=>p.id!==v.id));if(active?.id===v.id)onActivate(null)}}><Trash2 size={16}/> Eliminar</button></div></div></article>)}</div>{!vehicles.length&&<div className="garage-empty"><h2>Tu garaje está vacío.</h2><p>Puedes buscar sin vehículo o identificar uno nuevo.</p><button className="primary" onClick={onIdentify}>Identificar mi vehículo</button></div>}</main></div>}
